name: "basic_match"
replicaCount: 1

images:
  PullSecrets: 
    name: kartingreg
  repository: genesisproject.azurecr.io/basic-match
  tag: "latest"

service:
  type: ClusterIP
  ports:
  - name: http
    port: 3000

volume:
  - name: basic_match-volume-enums
    mountPath: /usr/src/app/dist/config/
    secretName: azure-secret
    shareName: system-genesis/  
    type: azurefile
   
  - name: basic_match-volume-fieldNames
    mountPath: /usr/src/app/dist/config/
    secretName: azure-secret
    shareName: system-genesis/  
    type: azurefile

config:
  configmaps: 
    name: basic_match
