name: "basic-match"
replicaCount: 1

images:
  PullSecrets: 
    name: kartingreg
  repository: genesisproject.azurecr.io/basic-match
  tag: "latest"

service:
  type: ClusterIP
  ports:
  - name: http
    port: 3000

volume:
  - name: mom
    mountPath: /spikeUtils
    secretName: azure-secret
    shareName: momentum/spike-utils
    type: azurefile

config:
  configmaps: 
    name: basic-match
